// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6_BeGNZW80FfrAB_KyJt18oRyEPpJbw',
    appId: '1:844996928045:web:0025b35f3f6d5660e18ea4',
    messagingSenderId: '844996928045',
    projectId: 'joomoonmoa',
    authDomain: 'joomoonmoa.firebaseapp.com',
    storageBucket: 'joomoonmoa.appspot.com',
    measurementId: 'G-E3LKSF59BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhPt4Ejhk6fzznjdcjLOPcxpVhG5S1AA',
    appId: '1:844996928045:android:d444e7c08aa443ede18ea4',
    messagingSenderId: '844996928045',
    projectId: 'joomoonmoa',
    storageBucket: 'joomoonmoa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzP519RqU44heXS4VoarhhCUrvf5mDIFo',
    appId: '1:844996928045:ios:9dff8d57a954c7afe18ea4',
    messagingSenderId: '844996928045',
    projectId: 'joomoonmoa',
    storageBucket: 'joomoonmoa.appspot.com',
    iosBundleId: 'com.joomoonmoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzP519RqU44heXS4VoarhhCUrvf5mDIFo',
    appId: '1:844996928045:ios:9dff8d57a954c7afe18ea4',
    messagingSenderId: '844996928045',
    projectId: 'joomoonmoa',
    storageBucket: 'joomoonmoa.appspot.com',
    iosBundleId: 'com.joomoonmoa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe6_BeGNZW80FfrAB_KyJt18oRyEPpJbw',
    appId: '1:844996928045:web:f91c0c82c9b2aaa5e18ea4',
    messagingSenderId: '844996928045',
    projectId: 'joomoonmoa',
    authDomain: 'joomoonmoa.firebaseapp.com',
    storageBucket: 'joomoonmoa.appspot.com',
    measurementId: 'G-NWX6Y5Z9Q4',
  );
}
